dpaste/models.py
import datetime
import random
import mptt
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from dpaste.highlight import LEXER_DEFAULT

t = 'abcdefghijkmnopqrstuvwwxyzABCDEFGHIJKLOMNOPQRSTUVWXYZ1234567890'
def generate_secret_id(length=5):
    return ''.join([random.choice(t) for i in range(length)])

class Snippet(models.Model):
    secret_id = models.CharField(_(u'Secret ID'), max_length=255, blank=True)
    content = models.TextField(_(u'Content'), )
    content_highlighted = models.TextField(_(u'Highlighted Content'), blank=True)
    lexer = models.CharField(_(u'Lexer'), max_length=30, default=LEXER_DEFAULT)
    published = models.DateTimeField(_(u'Published'), blank=True)
    expires = models.DateTimeField(_(u'Expires'), blank=True, help_text='asdf')
    parent = models.ForeignKey('self', null=True, blank=True, related_name='children')

    class Meta:
        ordering = ('-published',)
        db_table = 'dpaste_snippet'

    def get_linecount(self):
        return len(self.content.splitlines())

    def content_splitted(self):
        return self.content_highlighted.splitlines()

    @property
    def is_single(self):
        return self.is_root_node() and not self.get_children()

    def save(self, *args, **kwargs):
        if not self.pk:
            self.published = datetime.datetime.now()
            self.secret_id = generate_secret_id()
        self.content_highlighted = self.content
        super(Snippet, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('snippet_details', kwargs={'snippet_id': self.secret_id})

    def __unicode__(self):
        return '%s' % self.secret_id

mptt.register(Snippet, order_insertion_by=['content'])

dpaste/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from dpaste.models import Snippet
from dpaste.highlight import LEXER_LIST, LEXER_DEFAULT
import datetime

#===============================================================================
# Snippet Form and Handling
#===============================================================================

EXPIRE_CHOICES = (
    (3600, _(u'In one hour')),
    (3600 * 24 * 7, _(u'In one week')),
    (3600 * 24 * 30, _(u'In one month')),
)

EXPIRE_DEFAULT = 3600 * 24 * 30

MAX_CONTENT_LENGTH = getattr(settings, 'DPASTE_MAX_CONTENT_LENGTH', 250*1024*1024)

class SnippetForm(forms.ModelForm):
    content = forms.CharField(
        label=_('Content'),
        widget=forms.Textarea(attrs={'placeholder': _('Awesome code goes here...')}),
        max_length=MAX_CONTENT_LENGTH,
    )

    lexer = forms.ChoiceField(
        label=_(u'Lexer'),
        initial=LEXER_DEFAULT,
        widget=forms.TextInput,
    )

    expire_options = forms.ChoiceField(
        label=_(u'Expires'),
        choices=EXPIRE_CHOICES,
        initial=EXPIRE_DEFAULT,
    )

    # Honeypot field
    title = forms.CharField(
        label=_(u'Title'),
        required=False,
        widget=forms.TextInput(attrs={'autocomplete': 'off'}),
    )

    class Meta:
        model = Snippet
        fields = (
            'content',
            'lexer',
        )

    def __init__(self, request, *args, **kwargs):
        super(SnippetForm, self).__init__(*args, **kwargs)
        self.request = request
        self.fields['lexer'].choices = LEXER_LIST
        self.fields['lexer'].widget.attrs = {
            'autocomplete': 'off',
            'data-provide': 'typeahead',
            'data-source': '["%s"]' % '","'.join(dict(LEXER_LIST).keys())
        }

        # Set the recently used lexer if we have any
        session_lexer = self.request.session.get('lexer')
        if session_lexer and session_lexer in dict(LEXER_LIST).keys():
            self.fields['lexer'].initial = session_lexer

    def clean_lexer(self):
        lexer = self.cleaned_data.get('lexer')
        if not lexer:
            return LEXER_DEFAULT
        lexer = dict(LEXER_LIST).get(lexer, LEXER_DEFAULT)
        return lexer

    def clean_content(self):
        return self.cleaned_data.get('content', '').strip()

    def clean(self):
        if self.cleaned_data.get('title'):
            raise forms.ValidationError('This snippet was identified as Spam.')
        return self.cleaned_data

    def save(self, parent=None, *args, **kwargs):

        # Set parent snippet
        if parent:
            self.instance.parent = parent

        # Add expire datestamp
        self.instance.expires = datetime.datetime.now() + \
            datetime.timedelta(seconds=int(self.cleaned_data['expire_options']))

        # Save snippet in the db
        super(SnippetForm, self).save(*args, **kwargs)

        # Add the snippet to the user session list
        if self.request.session.get('snippet_list', False):
            if len(self.request.session['snippet_list']) >= getattr(settings, 'MAX_SNIPPETS_PER_USER', 10):
                self.request.session['snippet_list'].pop(0)
            self.request.session['snippet_list'] += [self.instance.pk]
        else:
            self.request.session['snippet_list'] = [self.instance.pk]

        # Save the lexer in the session so we can use it later again
        self.request.session['lexer'] = self.cleaned_data['lexer']

        return self.request, self.instance

dpaste/urls/__init__.py
from django.conf.urls.defaults import url, patterns, include
from django.views.generic import TemplateView

urlpatterns = patterns(
    '',
    url(r'^about/$', 'dpaste.views.about', name='about'),
    url(r'^', include('dpaste.urls.dpaste_api')),
    url(r'^', include('dpaste.urls.dpaste')),
)

# Custom error handlers which load `dpaste/<code>.html` instead of `<code>.html`
handler404 = 'dpaste.views.page_not_found'
handler500 = 'dpaste.views.server_error'

dpaste/views.py
import datetime
import difflib
import requests

from django.shortcuts import render_to_response, get_object_or_404, get_list_or_404
from django.template.context import RequestContext
from django.http import (Http404, HttpResponseRedirect, HttpResponseBadRequest,
                        HttpResponse, HttpResponseForbidden)
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.utils import simplejson
from django.db.models import Count
from django.views.defaults import (page_not_found as django_page_not_found,
                                   server_error as django_server_error)

from dpaste.forms import SnippetForm
from dpaste.models import Snippet
from dpaste.highlight import guess_code_lexer, \
    LEXER_WORDWRAP, LEXER_LIST



def about(request, template_name='dpaste/about.html'):
    template_context = {
        'total': Snippet.objects.count(),
        'stats': Snippet.objects.values('lexer').annotate(
            count=Count('lexer')).order_by('-count')[:5],
    }

    return render_to_response(
        template_name,
        template_context,
        RequestContext(request)
    )

def snippet_new(request, template_name='dpaste/snippet_new.html'):

    if request.method == "POST":
        snippet_form = SnippetForm(data=request.POST, request=request)
        if snippet_form.is_valid():
            request, new_snippet = snippet_form.save()
            url = new_snippet.get_absolute_url()
            return HttpResponseRedirect(url)
    else:
        snippet_form = SnippetForm(request=request)

    template_context = {
        'snippet_form': snippet_form,
        'is_new': True,
    }

    return render_to_response(
        template_name,
        template_context,
        RequestContext(request)
    )


def snippet_api(request, enclose_quotes=True):
    content = request.POST.get('content', '').strip()

    if not content:
        return HttpResponseBadRequest()

    s = Snippet.objects.create(
        content=content,
        expires=datetime.datetime.now()+datetime.timedelta(seconds=60*60*24*30)
    )
    s.save()

    response = 'http://dpaste.de%s' % s.get_absolute_url()
    if enclose_quotes:
        return HttpResponse('"%s"' % response)
    return HttpResponse(response)

def snippet_details(request, snippet_id, template_name='dpaste/snippet_details.html', is_raw=False):

    try:
        snippet = Snippet.objects.get(secret_id=snippet_id)
    except MultipleObjectsReturned:
        raise Http404('Multiple snippets exist for this slug. This should never '
                      'happen but its likely that you are a spam bot, so I dont '
                      'care.')
    except ObjectDoesNotExist:
        raise Http404('This snippet does not exist anymore. Its likely that its '
                      'lifetime is expired.')

    tree = snippet.get_root()
    tree = tree.get_descendants(include_self=True)

    new_snippet_initial = {
        'content': snippet.content,
        'lexer': snippet.lexer,
    }

    if request.method == "POST":
        snippet_form = SnippetForm(data=request.POST, request=request, initial=new_snippet_initial)
        if snippet_form.is_valid():
            request, new_snippet = snippet_form.save(parent=snippet)
            url = new_snippet.get_absolute_url()
            return HttpResponseRedirect(url)
    else:
        snippet_form = SnippetForm(initial=new_snippet_initial, request=request)

    template_context = {
        'snippet_form': snippet_form,
        'snippet': snippet,
        'lexers': LEXER_LIST,
        'lines': range(snippet.get_linecount()),
        'tree': tree,
        'wordwrap': snippet.lexer in LEXER_WORDWRAP and 'True' or 'False',
    }

    response = render_to_response(
        template_name,
        template_context,
        RequestContext(request)
    )

    if is_raw:
        response['Content-Type'] = 'text/plain;charset=UTF-8'
        return response
    else:
        return response

def snippet_delete(request, snippet_id=None):
    snippet_id = snippet_id or request.POST.get('snippet_id')
    if not snippet_id:
        return HttpResponseBadRequest('No snippet given!')

    snippet = get_object_or_404(Snippet, secret_id=snippet_id)
    """
    Anybody can delete anybodys snippets now.

    try:
        snippet_list = request.session['snippet_list']
    except KeyError:
        return HttpResponseForbidden('You have no recent snippet list, cookie error?')
    if not snippet.pk in snippet_list:
        return HttpResponseForbidden('That\'s not your snippet!')
    """
    snippet.delete()
    return HttpResponseRedirect(reverse('snippet_new') + '?delete=1')

def snippet_history(request, template_name='dpaste/snippet_list.html'):

    try:
        snippet_list = get_list_or_404(Snippet, pk__in=request.session.get('snippet_list', None))
    except ValueError:
        snippet_list = None

    template_context = {
        'snippets_max': getattr(settings, 'MAX_SNIPPETS_PER_USER', 10),
        'snippet_list': snippet_list,
    }

    return render_to_response(
        template_name,
        template_context,
        RequestContext(request)
    )


def snippet_diff(request, template_name='dpaste/snippet_diff.html'):

    if request.GET.get('a') and request.GET.get('a').isdigit() \
    and request.GET.get('b') and request.GET.get('b').isdigit():
        try:
            fileA = Snippet.objects.get(pk=int(request.GET.get('a')))
            fileB = Snippet.objects.get(pk=int(request.GET.get('b')))
        except ObjectDoesNotExist:
            return HttpResponseBadRequest(u'Selected file(s) does not exist.')
    else:
        return HttpResponseBadRequest(u'You must select two snippets.')

    class DiffText(object):
        pass

    diff = DiffText()

    if fileA.content != fileB.content:
        d = difflib.unified_diff(
            fileA.content.splitlines(),
            fileB.content.splitlines(),
            'Original',
            'Current',
            lineterm=''
        )

        diff.content = '\n'.join(d).strip()
        diff.lexer = 'diff'
    else:
        diff.content = _(u'No changes were made between this two files.')
        diff.lexer = 'text'

    template_context = {
        'snippet': diff,
        'fileA': fileA,
        'fileB': fileB,
    }

    return render_to_response(
        template_name,
        template_context,
        RequestContext(request)
    )

def snippet_gist(request, snippet_id):
    """
    Put a snippet on Github Gist.
    """
    snippet = get_object_or_404(Snippet, secret_id=snippet_id)
    data = {
        'description': 'the description for this gist',
        'public': False,
        'files': {
            'dpaste.de_snippet.py': {
                'content': snippet.content,
            }
        }
    }

    try:
        payload = simplejson.dumps(data)
        response = requests.post('https://api.github.com/gists', data=payload)
        response_dict = simplejson.loads(response.content)
        gist_url = response_dict.get('html_url')

    # Github could be down, could return invalid JSON, it's rare
    except:
        return HttpResponse('Creating a Github Gist failed. Sorry, please go back and try again.')

    return HttpResponseRedirect(gist_url)



def guess_lexer(request):
    code_string = request.GET.get('codestring', False)
    response = simplejson.dumps({'lexer': guess_code_lexer(code_string)})
    return HttpResponse(response)


def page_not_found(request, template_name='dpaste/404.html'):
    return django_page_not_found(request, template_name)

def server_error(request, template_name='dpaste/500.html'):
    return django_server_error(request, template_name)

dpaste/templates/dpaste/base.html
{% load i18n staticfiles %}<!DOCTYPE html>
<html>
<head>
    <title>dpaste.de: {% block title %}{% trans "New snippet" %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "dpaste/bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "dpaste/theme.css" %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% block extrahead %}{% endblock %}
</head>
<body>

<div class="container-fluid">
    <header>
        <ul class="nav nav-pills pull-right">
            <li class="{% block dpaste_nav_about %}{% endblock %}"><a href="{% url "about" %}">{% trans "About" %}</a></li>
            <li class="{% block dpaste_nav_history %}{% endblock %}"><a href="{% url "snippet_history" %}">{% trans "History" %}</a></li>
            <li class="{% block dpaste_nav_new %}{% endblock %}"><a href="{% url "snippet_new" %}">{% trans "New snippet" %} &rarr;</a></li>
        </ul>
        <h3 class="headline">{% block headline %}{% endblock %}</h3>
    </header>

    <hr>

    {% block page %}
        PAGE MISSING
    {% endblock %}
</div>

{% block script_footer %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
<script src="{% static "dpaste/bootstrap/js/bootstrap.min.js" %}"></script>
<script>
jQuery(function($) {
    var lexerReq;
    $('#guess_lexer_btn').click(function() {
        // Cancel previous request if it is still pending
        if (lexerReq) {
            lexerReq.abort();
        }

        lexerReq = $.getJSON('{% url "snippet_guess_lexer" %}', {
            codestring: $('#id_content').val()
        }).done(function(data) {
            if (data.lexer === 'unknown') {
                $('#guess_lexer_btn').css('color', 'red');
            } else {
                $('#id_lexer').val(data.lexer);
                $('#guess_lexer_btn').css('color', 'inherit');
            }
        }).complete(function() {
            lexerReq = null;
        });
    });

    $('.autofocus input:text, .autofocus textarea').first().focus();
});
</script>
{% endblock %}

</body>
</html>

dpaste/templates/dpaste/snippet_details.html
{% extends "dpaste/base.html" %}
{% load mptt_tags %}
{% load i18n %}
{% load dpaste_tags %}

{% block title %}{% trans "Snippet" %} #{{ snippet.pk }}{% endblock %}
{% block headline %}{% trans "Snippet" %} #{{ snippet.pk }}{% endblock %}

{% block page %}

    <!-- ======================================================================
    Snippet Diff View
    ======================================================================= -->
    <div id="snippet-diff" class="snippet-diff container-fluid">
        <div class="row-fluid">
            <div class="span9">
                <div id="diff" style="display:none;"></div>
            </div>
            <div class="span3">
                <form method="get" id="diffform" action="{% url "snippet_diff" %}">
                {% csrf_token %}
                <div class="tree">
                    {% for tree_item,structure in tree|tree_info %}
                    {% if structure.new_level %}<ul><li>{% else %}</li><li>{% endif %}
                    <div>
                    <span class="diff">
                        <input type="radio" name="a" value="{{ tree_item.id }}" {% ifequal tree_item.id snippet.parent_id %}checked="checked"{% endifequal %}>
                        <input type="radio" name="b" value="{{ tree_item.id }}" {% ifequal snippet tree_item %}checked="checked"{% endifequal %}>
                    </span>
                    {% ifequal snippet tree_item %}
                        <strong>#{{ tree_item.id }}</strong>
                   {% else %}
                   <a href="{{ tree_item.get_absolute_url }}">#{{ tree_item.id }}</a>
                    {% endifequal %}
                    </div>
                    {% for level in structure.closed_levels %}</li></ul>{% endfor %}
                    {% endfor %}
                    <div class="submit">
                        <input type="submit" value="{% trans "Compare" %}">
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>

    <!-- ======================================================================
    Snippet Options
    ======================================================================= -->
    <div class="btn-group snippet-options">
        <button disabled class="btn">Expires in: {{ snippet.expires|timeuntil  }}</button>
        {% if snippet.pk|in_list:request.session.snippet_list %}
        <a class="btn" href="{% url "snippet_delete" snippet.secret_id %}" onclick="return confirm('{% trans "Really delete this snippet?" %}');"><i class="icon-trash"></i> {% trans "Delete Now" %}</a>
        {% endif %}
        {% if not snippet.is_single %}
        <a class="btn snippet-diff-trigger" href="#snippet-diff"><i class="icon-search"></i> {% trans "Compare Snippets" %}</a>
        {% endif %}
        <a class="btn" href="{% url "snippet_details_raw" snippet.secret_id %}"><i class="icon-align-left"></i> {% trans "View Raw" %}</a>
        <a class="btn" href="{% url "snippet_gist" snippet.secret_id %}"
            rel="nofollow" title="Create a secret Gist"><i class="icon-share"></i> {% trans "Gist" %}</a>
    </div>

    <!-- ======================================================================
    Snippet
    ======================================================================= -->
    {% include "dpaste/snippet_pre.html" %}

    <!-- ======================================================================
    Snippet Reply
    ======================================================================= -->
    <hr>

    <div class="snippet-reply snippet-reply-hidden">
        <h3>{% trans "Reply to this snippet" %} &rarr;</h3>
        {% include "dpaste/snippet_form.html" %}
    </div>
{% endblock %}


{% block script_footer %}
{{ block.super }}
<script>
jQuery(function($) {
    var diffReq;

    $('.snippet-reply-hidden').click(function(e) {
        $(this).removeClass('snippet-reply-hidden');
    });

    /**
     * Diff Ajax Call
     */
    $('.snippet-diff-trigger').click(function(e) {
        e.preventDefault();
        $('#snippet-diff').slideDown('fast');
        $('#snippet-diff form').submit();
    });


    $('#diffform').submit(function() {
        var a = $('input[name="a"]:checked').val(),
            b = $('input[name="b"]:checked').val();

        window.location.hash = 'D' + a + ',' + b;

        // Cancel previous request if it is still pending
        if (diffReq) {
            diffReq.abort();
        }

        diffReq = $.get("{% url "snippet_diff" %}", {
            a: a,
            b: b
        }).done(function(data) {
            $('#diff').html(data).slideDown('fast');
        }).complete(function() {
            diffReq = null;
        });

        return false;
    });

    var curLine = document.location.hash,
        hashlist;

    if (curLine.substring(0, 2) === '#D') {
        hashlist = curLine.substring(2).split(',');
        if (hashlist.length === 2) {
            console.log(hashlist);
            $('#diffform input[name="a"][value="' + hashlist[0] + '"]').prop('checked', true);
            $('#diffform input[name="b"][value="' + hashlist[1] + '"]').prop('checked', true);
            $('#snippet-diff').slideDown('fast');
            $('#snippet-diff form').submit();
        }
    }

    /**
     * Line Highlighting
     */

    if (curLine.substring(0, 2) === '#L') {
        hashlist = curLine.substring(2).split(',');
        if (hashlist.length > 0 && hashlist[0] !== '') {
            $.each(hashlist, function(index, elem){
                $('.linenums li#' + elem).addClass('marked');
            });
        }
    }

    $('.linenums li').click(function(e) {
        var line = $(this),
            hash = 'L';

        line.toggleClass('marked');

        $('.linenums li.marked').each(function (index, elem) {
            if (hash !== 'L') hash += ',';
            hash += $(elem).attr('id');
        });

        window.location.hash = hash;
    });
});
</script>
{% endblock %}

dpaste/templates/dpaste/snippet_details_raw.html
{{ snippet.content|safe }}

dpaste/templates/dpaste/snippet_diff.html
{% load i18n %}

<h4>
    {% blocktrans with fileA.get_absolute_url as filea_url and fileB.get_absolute_url as fileb_url and fileA.id as filea_id and fileB.id as fileb_id %}
    Diff between <a href="{{ filea_url }}">#{{ filea_id }}</a> and <a href="{{ fileb_url }}">#{{ fileb_id }}</a>
    {% endblocktrans %}
</h4>

{% if snippet.lexer == 'diff' %}
    {% include "dpaste/snippet_pre.html" %}
{% else %}
    <p>{{ snippet.content }}</p>
{% endif %}

dpaste/templates/dpaste/snippet_form.html
{% load i18n %}

<form method="post" action="" class="form-horizontal">
    {% csrf_token %}
    {{ snippet_form.non_field_errors }}
    <div style="display: none;">{{ snippet_form.title }}</div>

    <div class="
        control-group
        form-content
        {% if is_new %}autofocus{% endif %}
        {% if snippet_form.content.errors %}error{% endif %}
    ">
        {{ snippet_form.content }}
    </div>

    <div class="control-group form-options">
        <div class="form-options-lexer
            {% if snippet_form.lexer.errors %}control-group error{% endif %}">
            <div class="input-append">
                {{ snippet_form.lexer }}
                <button class="btn" id="guess_lexer_btn" type="button">{% trans "Guess lexer" %}</button>
            </div>
            {% for error in snippet_form.lexer.errors %}
            <span class="help-inline">{{ error }}</span>
            {% endfor %}
        </div>
        <div class="form-options-expire">
            {{ snippet_form.expire_options.errors }}
            <div class="input-prepend">
                <span class="add-on"><i class="icon-trash" title="{% trans "Expire in" %}"></i></span>
                {{ snippet_form.expire_options }}
            </div>
        </div>
    </div>
    <div class="form-actions">
        {% if is_new %}
        <div class="twitter-follow-button-container">
            <a href="https://twitter.com/bartTC" class="twitter-follow-button" data-show-count="false" data-size="large" data-dnt="true">Follow @bartTC</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </div>
        {% endif %}
        <input tabindex="0" type="submit"class="btn btn-primary" value="{% trans "Paste it" %}">
    </div>
</form>

dpaste/templates/dpaste/snippet_list.html
{% extends "dpaste/base.html" %}
{% load i18n %}
{% load dpaste_tags %}

{% block title %}Snippet History{% endblock %}
{% block headline %}Snippet History{% endblock %}
{% block dpaste_nav_history %}active{% endblock %}
{% block page %}
    {% for snippet in snippet_list %}
    <h4>
        <a title="{{ snippet.published|date:_("DATETIME_FORMAT") }}" href="{{ snippet.get_absolute_url }}">
            {% blocktrans with snippet.published|timesince as since %}{{ since }} ago{% endblocktrans %}
        </a>
    </h4>
    {% include "dpaste/snippet_pre.html" %}
    {% if not forloop.last %}<hr>{% endif %}
    {% empty %}
    <p>{% trans "No snippets saved. Either all your snippets are expired or your cookie has changed." %}</p>
    {% endfor %}
{% endblock %}

dpaste/templates/dpaste/snippet_new.html
{% extends "dpaste/base.html" %}
{% load i18n %}

{% block title %}{% trans "New snippet" %}{% endblock %}
{% block headline %}{% trans "New snippet" %}{% endblock %}
{% block dpaste_nav_new %}active{% endblock %}

{% block page %}
    {% include "dpaste/snippet_form.html" %}
{% endblock %}

dpaste/templates/dpaste/snippet_pre.html
{% load dpaste_tags %}<pre class="prettyprint linenums"><ol class="linenums">{% for line in snippet|highlight %}<li id="{{ forloop.counter }}">{{ line|safe|default:"&nbsp;" }}</li>{% endfor %}</ol></pre>